# Generated by Django 3.2.25 on 2024-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField(default=9845671230)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField(default=0)),
                ('design', models.CharField(default='Employee', max_length=100)),
            ],
        ),
    ]
