# Generated by Django 3.2.25 on 2024-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_num',
            field=models.IntegerField(max_length=10),
        ),
    ]
