# Generated by Django 3.2.25 on 2024-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_alter_employees_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
