# Generated by Django 3.2.25 on 2024-03-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_employees_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_img',
            field=models.ImageField(default=1, upload_to='employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
